options:
  cuda-version:
    type: string
    default: "9.1.85-1"
    description: |
      The cuda-repo package version to install.
  install-cuda:
    type: boolean
    default: True
    description: |
      Install the CUDA drivers if capable hardware is present.
