options:
  cuda-version:
    type: string
    default: "8.0.61-1"
    description: |
      The cuda-repo package version to install.
  install-cuda:
    type: boolean
    default: True
    description: |
      Install the CUDA binaries if capable hardware is present.
