options:
  cuda-version:
    type: string
    default: "9.1.85-1"
    description: |
      Version of the cuda-repo deb to install. Valid options can be found at:
      http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64
  install-cuda:
    type: boolean
    default: True
    description: |
      Install the CUDA binaries if capable hardware is present.
